#!/bin/bash -eu
check_ignore() {
  local -a files=(
    ".git"
    ".gitignore"
    ".DS_Store"
  )

  local file
  for file in ${files[@]}; do
    [[ $1 = ${file} ]] && return 0
  done

  return 1
}

link_files() {
  for f in .??*
  do
    check_ignore ${f} && continue

    # Force remove the vim directory if it's already there
    [ -n "${OVERWRITE}" -a -e ${HOME}/${f} ] && rm -f ${HOME}/${f}
    if [ ! -e ${HOME}/${f} ]; then
      # If you have ignore files, add file/directory name here
      ln -snfv ${DOT_DIRECTORY}/${f} ${HOME}/${f}
    fi
  done

  # vscode
  local vscode_dir="${HOME}/Library/Application Support/Code/User"
  [ -n "${OVERWRITE}" -a -e "${vscode_dir}" ] && rm -f "${vscode_dir}"
  if [ ! -e "${vscode_dir}" ]; then
    ln -snfv ${DOT_DIRECTORY}/vscode/User "${vscode_dir}"
  fi

  echo $(tput setaf 2)Deploy dotfiles complete!. ✔︎$(tput sgr0)
}
