#!/bin/bash -eu
initialize() {
  case ${OSTYPE} in
    darwin*)
      run_defaults
      run_brew

      set +e
      if [ ! -e ~/Library/Fonts/Cica-Regular.ttf ]; then
        CICA_VIRSION="v4.1.1"
        wget https://github.com/miiton/Cica/releases/download/${CICA_VIRSION}/Cica-${CICA_VIRSION}.zip
        unar Cica-${CICA_VIRSION}.zip
        cp -f Cica-${CICA_VIRSION}/Cica*.ttf ${HOME}/Library/Fonts/
        rm -rf Cica-${CICA_VIRSION}*
      fi
      set -e
      ;;
    linux-gnu)
      ID_LIKE=`grep -h "ID_LIKE" /etc/os-release | awk -F= '{print $2}'`
      case $ID_LIKE in
        *debian*)
          run_apt
          ;;
        *fedora*)
          echo $(tput setaf 1)Working only OSX / Ubuntu!!$(tput sgr0)
          exit 1
          ;;
        *)
          echo $(tput setaf 1)Working only OSX / Ubuntu!!$(tput sgr0)
          exit 1
          ;;
      esac
      ;;
    *)
      echo $(tput setaf 1)Working only OSX / Ubuntu!!$(tput sgr0)
      exit 1
      ;;
  esac

  set +e
  bash <(curl https://raw.githubusercontent.com/Shougo/dein.vim/master/bin/installer.sh) ~/.cache/dein

  if has "fish"; then
    ${DOT_DIRECTORY}/.config/fish/functions/install_fisher.fish
  fi

  if  has "anyenv"; then
    init_anyenv
  fi

  if has "apm"; then
    apm install --packages-file atom/packages.list
  fi

  set -e

  echo "$(tput setaf 2)Initialize complete!. ✔︎$(tput sgr0)"
}
