#!/bin/bash -eu

function source_dir() {
  for item in "$@"/*; do
    if [ -f "$item" ]; then
      # shellcheck source=/dev/null
      source "$item"
    fi
  done
}

function setup_formurae() {
  source_dir "${DOT_DIRECTORY}"/lib/formulae

  setup_fish
  init_anyenv
  install_atom_packages
  setup_vscode
}

run_brew() {
  if has "brew"; then
    echo "$(tput setaf 2)Already installed Homebrew ✔︎$(tput sgr0)"
  else
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
  fi

  if has "brew"; then
    echo "Updating Homebrew..."
    brew update && brew upgrade
    [[ $? ]] && echo "$(tput setaf 2)Update Homebrew complete. ✔︎$(tput sgr0)"

    echo "Installing Homebrew formulae..."
    brew bundle --global
    [[ $? ]] && echo "$(tput setaf 2)Installed formulae ✔︎$(tput sgr0)"

    echo "Cleanup Homebrew..."
    brew cleanup
    echo "$(tput setaf 2)Cleanup Homebrew complete. ✔︎$(tput sgr0)"
  fi
}
