#!/bin/bash

function setup_vscode() {
  if [ -d "${VSCODE_PATH}" ]; then
    export PATH="${PATH}:${VSCODE_PATH}"
    xargs -L 1 code --install-extension <"${DOT_DIRECTORY}/vscode/packages.list"
    local VSCODE_DIR="${HOME}/Library/Application Support/Code/User"
    [ -n "${OVERWRITE}" ] && [ -e "${VSCODE_DIR}" ] && rm -f "${VSCODE_DIR}"
    if [ ! -e "${VSCODE_DIR}" ]; then
      ln -snfv "${DOT_DIRECTORY}/vscode/User" "${VSCODE_DIR}"
    fi
  fi
}
